POST https://fakhrul.azurewebsites.net/loginHost
Content-Type: application/json

{
  "idNumber": "20223112",
  "password": "12345"
}

###
### POST Request to viewVisitor Endpoint
###

POST http://localhost:3000/viewVisitor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEyIiwicm9sZSI6Im93bmVyIiwiaWF0IjoxNzA0NTM4ODYzfQ.twmOo7M8bEFveUYRId2UOQ2IYsVoMP8HkqOrmDUDQOI

###

POST http://localhost:3000/retrieveVisitor
Content-Type: application/json

{
  "idNumber": "psj123"
}

###

POST http://localhost:3000/loginAdmin
Content-Type: application/json

{
  "idNumber": "20223110",
  "password": "12345"
}

###

POST http://localhost:3000/loginSecurity
Content-Type: application/json

{
  "idNumber": "56789",
  "password": "awang123"
}

###

POST http://localhost:3000/loginHost
Content-Type: application/json

{
  "idNumber": "cheng123",
  "password": "#Cheng123"
}

###

POST http://localhost:3000/issuepassVisitor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEzIiwicm9sZSI6InNlY3VyaXR5IiwiaWF0IjoxNzA1NDEyNDM4fQ.1sWqfW-ADc5zxFw0C7bklKiq8s7QojylYLOZu0IkBuE
{
  "role": "visitor",
  "name": "Baran", 
  "idNumber": "baran123",
  "documentType": "Mykad",
  "gender": "Male",
  "birthDate": "2003-03-10",
  "age": "51",
  "documentExpiry": "2028-04-03",
  "company": "Kepala",
  "TelephoneNumber": "019236451",
  "vehicleNumber": "YHB678",
  "category": "Friend",
  "ethnicity": "Indian",
  "photoAttributes": "Photo Attributes",
  "passNumber": "095",
  "password": "1234",
  "idNumberHost": "20223112"
}

###

POST http://localhost:3000/registerHost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEzIiwicm9sZSI6InNlY3VyaXR5IiwiaWF0IjoxNzA0NTQ4MDk2fQ.9z86tA_YIRnTanX4C9lm5HfbakJDZhGyGqMOVZ6y0r4

{
  "role": "Host",
  "name": "Seo",
  "idNumber": "seo123",
  "email": "seo@email.com",
  "password": "#Seo12345",
  "phoneNumber": "0218413531"
}

###

POST http://localhost:3000/registertestHost
Content-Type: application/json

{
  "role": "Host",
  "name": "Seo",
  "idNumber": "seo123",
  "email": "seo@email.com",
  "password": "3",
  "phoneNumber": "0218413531"
}

###

POST http://localhost:3000/viewHost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTE5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NTUwNDg2fQ.kD7E7Wf33BQyN_omJEzVg9a5tPXy_0cFmJcDEYnXR1Q

###

POST http://localhost:3000/manageRole
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTE5Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzA0NTU1NTAzfQ.9qK3vocFS68JRntEBQJ0z6mHp4lZ3PbZkW8BRkLb868

{
  "idNumber": "345657890",
  "role": "security"
}

###

POST http://localhost:3000/loginAdmin
Content-Type: application/json

{
  "idNumber": "20223119",
  "password": "67890"
}

###

POST http://localhost:3000/retrieveHostContact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEzIiwicm9sZSI6InNlY3VyaXR5IiwiaWF0IjoxNzA1MzgwNzM0fQ.-kVOvtqRBiQUny1S98SZ_Jmge78dCY8yAkKI8O2IjIE

{
  "visitorPassNumber": "021"
}

###

DELETE http://localhost:3000/deleteVisitor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZE51bWJlciI6IjIwMjIzMTEyIiwicm9sZSI6Ikhvc3QiLCJpYXQiOjE3MDUzODYxMTd9.sZWZTeB82jLVlXeNC2N6rEU8Pgsu3dBU6EnvZDlBilU

{
  "passNumber": "001"
}
