POST https://benr3433-vms.azurewebsites.net/loginOwner
Content-Type: application/json

{
    "idNumber": "20223112",
    "password": "12345"
}

# GET /viewVisitor
###

# Request to viewVisitor endpoint
GET http://localhost:3000/viewVisitor
Authorization: Bearer your-token-here

# Response should be printed below
